/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // 颜色定义 - 完整色板映射
        primary: {
          DEFAULT: 'oklch(var(--color-primary) / <alpha-value>)',
          50: 'oklch(var(--color-primary-50) / <alpha-value>)',
          100: 'oklch(var(--color-primary-100) / <alpha-value>)',
          200: 'oklch(var(--color-primary-200) / <alpha-value>)',
          300: 'oklch(var(--color-primary-300) / <alpha-value>)',
          400: 'oklch(var(--color-primary-400) / <alpha-value>)',
          500: 'oklch(var(--color-primary-500) / <alpha-value>)',
          600: 'oklch(var(--color-primary-600) / <alpha-value>)',
          700: 'oklch(var(--color-primary-700) / <alpha-value>)',
          800: 'oklch(var(--color-primary-800) / <alpha-value>)',
          900: 'oklch(var(--color-primary-900) / <alpha-value>)',
        },
        gray: {
          DEFAULT: 'oklch(var(--color-gray) / <alpha-value>)',
          50: 'oklch(var(--color-gray-50) / <alpha-value>)',
          100: 'oklch(var(--color-gray-100) / <alpha-value>)',
          200: 'oklch(var(--color-gray-200) / <alpha-value>)',
          300: 'oklch(var(--color-gray-300) / <alpha-value>)',
          400: 'oklch(var(--color-gray-400) / <alpha-value>)',
          500: 'oklch(var(--color-gray-500) / <alpha-value>)',
          600: 'oklch(var(--color-gray-600) / <alpha-value>)',
          700: 'oklch(var(--color-gray-700) / <alpha-value>)',
          800: 'oklch(var(--color-gray-800) / <alpha-value>)',
          900: 'oklch(var(--color-gray-900) / <alpha-value>)',
        },
        blue: {
          DEFAULT: 'oklch(var(--color-blue) / <alpha-value>)',
          50: 'oklch(var(--color-blue-50) / <alpha-value>)',
          100: 'oklch(var(--color-blue-100) / <alpha-value>)',
          200: 'oklch(var(--color-blue-200) / <alpha-value>)',
          300: 'oklch(var(--color-blue-300) / <alpha-value>)',
          400: 'oklch(var(--color-blue-400) / <alpha-value>)',
          500: 'oklch(var(--color-blue-500) / <alpha-value>)',
          600: 'oklch(var(--color-blue-600) / <alpha-value>)',
          700: 'oklch(var(--color-blue-700) / <alpha-value>)',
          800: 'oklch(var(--color-blue-800) / <alpha-value>)',
          900: 'oklch(var(--color-blue-900) / <alpha-value>)',
        },
        red: {
          DEFAULT: 'oklch(var(--color-red) / <alpha-value>)',
          50: 'oklch(var(--color-red-50) / <alpha-value>)',
          100: 'oklch(var(--color-red-100) / <alpha-value>)',
          200: 'oklch(var(--color-red-200) / <alpha-value>)',
          300: 'oklch(var(--color-red-300) / <alpha-value>)',
          400: 'oklch(var(--color-red-400) / <alpha-value>)',
          500: 'oklch(var(--color-red-500) / <alpha-value>)',
          600: 'oklch(var(--color-red-600) / <alpha-value>)',
          700: 'oklch(var(--color-red-700) / <alpha-value>)',
          800: 'oklch(var(--color-red-800) / <alpha-value>)',
          900: 'oklch(var(--color-red-900) / <alpha-value>)',
        },
        orange: {
          DEFAULT: 'oklch(var(--color-orange) / <alpha-value>)',
          50: 'oklch(var(--color-orange-50) / <alpha-value>)',
          100: 'oklch(var(--color-orange-100) / <alpha-value>)',
          200: 'oklch(var(--color-orange-200) / <alpha-value>)',
          300: 'oklch(var(--color-orange-300) / <alpha-value>)',
          400: 'oklch(var(--color-orange-400) / <alpha-value>)',
          500: 'oklch(var(--color-orange-500) / <alpha-value>)',
          600: 'oklch(var(--color-orange-600) / <alpha-value>)',
          700: 'oklch(var(--color-orange-700) / <alpha-value>)',
          800: 'oklch(var(--color-orange-800) / <alpha-value>)',
          900: 'oklch(var(--color-orange-900) / <alpha-value>)',
        },
        yellow: {
          DEFAULT: 'oklch(var(--color-yellow) / <alpha-value>)',
          50: 'oklch(var(--color-yellow-50) / <alpha-value>)',
          100: 'oklch(var(--color-yellow-100) / <alpha-value>)',
          200: 'oklch(var(--color-yellow-200) / <alpha-value>)',
          300: 'oklch(var(--color-yellow-300) / <alpha-value>)',
          400: 'oklch(var(--color-yellow-400) / <alpha-value>)',
          500: 'oklch(var(--color-yellow-500) / <alpha-value>)',
          600: 'oklch(var(--color-yellow-600) / <alpha-value>)',
          700: 'oklch(var(--color-yellow-700) / <alpha-value>)',
          800: 'oklch(var(--color-yellow-800) / <alpha-value>)',
          900: 'oklch(var(--color-yellow-900) / <alpha-value>)',
        },
        green: {
          DEFAULT: 'oklch(var(--color-green) / <alpha-value>)',
          50: 'oklch(var(--color-green-50) / <alpha-value>)',
          100: 'oklch(var(--color-green-100) / <alpha-value>)',
          200: 'oklch(var(--color-green-200) / <alpha-value>)',
          300: 'oklch(var(--color-green-300) / <alpha-value>)',
          400: 'oklch(var(--color-green-400) / <alpha-value>)',
          500: 'oklch(var(--color-green-500) / <alpha-value>)',
          600: 'oklch(var(--color-green-600) / <alpha-value>)',
          700: 'oklch(var(--color-green-700) / <alpha-value>)',
          800: 'oklch(var(--color-green-800) / <alpha-value>)',
          900: 'oklch(var(--color-green-900) / <alpha-value>)',
        },
        indigo: {
          DEFAULT: 'oklch(var(--color-indigo) / <alpha-value>)',
          50: 'oklch(var(--color-indigo-50) / <alpha-value>)',
          100: 'oklch(var(--color-indigo-100) / <alpha-value>)',
          200: 'oklch(var(--color-indigo-200) / <alpha-value>)',
          300: 'oklch(var(--color-indigo-300) / <alpha-value>)',
          400: 'oklch(var(--color-indigo-400) / <alpha-value>)',
          500: 'oklch(var(--color-indigo-500) / <alpha-value>)',
          600: 'oklch(var(--color-indigo-600) / <alpha-value>)',
          700: 'oklch(var(--color-indigo-700) / <alpha-value>)',
          800: 'oklch(var(--color-indigo-800) / <alpha-value>)',
          900: 'oklch(var(--color-indigo-900) / <alpha-value>)',
        },
        purple: {
          DEFAULT: 'oklch(var(--color-purple) / <alpha-value>)',
          50: 'oklch(var(--color-purple-50) / <alpha-value>)',
          100: 'oklch(var(--color-purple-100) / <alpha-value>)',
          200: 'oklch(var(--color-purple-200) / <alpha-value>)',
          300: 'oklch(var(--color-purple-300) / <alpha-value>)',
          400: 'oklch(var(--color-purple-400) / <alpha-value>)',
          500: 'oklch(var(--color-purple-500) / <alpha-value>)',
          600: 'oklch(var(--color-purple-600) / <alpha-value>)',
          700: 'oklch(var(--color-purple-700) / <alpha-value>)',
          800: 'oklch(var(--color-purple-800) / <alpha-value>)',
          900: 'oklch(var(--color-purple-900) / <alpha-value>)',
        },
        pink: {
          DEFAULT: 'oklch(var(--color-pink) / <alpha-value>)',
          50: 'oklch(var(--color-pink-50) / <alpha-value>)',
          100: 'oklch(var(--color-pink-100) / <alpha-value>)',
          200: 'oklch(var(--color-pink-200) / <alpha-value>)',
          300: 'oklch(var(--color-pink-300) / <alpha-value>)',
          400: 'oklch(var(--color-pink-400) / <alpha-value>)',
          500: 'oklch(var(--color-pink-500) / <alpha-value>)',
          600: 'oklch(var(--color-pink-600) / <alpha-value>)',
          700: 'oklch(var(--color-pink-700) / <alpha-value>)',
          800: 'oklch(var(--color-pink-800) / <alpha-value>)',
          900: 'oklch(var(--color-pink-900) / <alpha-value>)',
        },
        black: 'rgb(var(--color-black) / <alpha-value>)',
        white: 'rgb(var(--color-white) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
