export const COUNTRIES = [
  // --- 亚洲 Asia ---
  { countryName: '中国', phoneCode: '+86', countryCode: 'CN' },
  { countryName: '日本', phoneCode: '+81', countryCode: 'JP' },
  { countryName: '韩国', phoneCode: '+82', countryCode: 'KR' },
  { countryName: '新加坡', phoneCode: '+65', countryCode: 'SG' },
  { countryName: '香港', phoneCode: '+852', countryCode: 'HK' },
  { countryName: '台湾', phoneCode: '+886', countryCode: 'TW' },
  { countryName: '印度', phoneCode: '+91', countryCode: 'IN' },
  { countryName: '马来西亚', phoneCode: '+60', countryCode: 'MY' },
  { countryName: '泰国', phoneCode: '+66', countryCode: 'TH' },
  { countryName: '越南', phoneCode: '+84', countryCode: 'VN' },
  { countryName: '菲律宾', phoneCode: '+63', countryCode: 'PH' },
  { countryName: '印度尼西亚', phoneCode: '+62', countryCode: 'ID' },
  { countryName: '巴基斯坦', phoneCode: '+92', countryCode: 'PK' },
  { countryName: '孟加拉国', phoneCode: '+880', countryCode: 'BD' },
  { countryName: '伊朗', phoneCode: '+98', countryCode: 'IR' },
  { countryName: '哈萨克斯坦', phoneCode: '+7', countryCode: 'KZ' },
  { countryName: '乌兹别克斯坦', phoneCode: '+998', countryCode: 'UZ' },
  { countryName: '斯里兰卡', phoneCode: '+94', countryCode: 'LK' },
  { countryName: '缅甸', phoneCode: '+95', countryCode: 'MM' },
  { countryName: '柬埔寨', phoneCode: '+855', countryCode: 'KH' },
  { countryName: '尼泊尔', phoneCode: '+977', countryCode: 'NP' },

  // --- 北美洲 North America ---
  { countryName: '美国', phoneCode: '+1', countryCode: 'US' },
  { countryName: '加拿大', phoneCode: '+1', countryCode: 'CA' },
  { countryName: '墨西哥', phoneCode: '+52', countryCode: 'MX' },

  // --- 欧洲 Europe ---
  { countryName: '英国', phoneCode: '+44', countryCode: 'GB' },
  { countryName: '德国', phoneCode: '+49', countryCode: 'DE' },
  { countryName: '法国', phoneCode: '+33', countryCode: 'FR' },
  { countryName: '俄罗斯', phoneCode: '+7', countryCode: 'RU' },
  { countryName: '意大利', phoneCode: '+39', countryCode: 'IT' },
  { countryName: '西班牙', phoneCode: '+34', countryCode: 'ES' },
  { countryName: '荷兰', phoneCode: '+31', countryCode: 'NL' },
  { countryName: '瑞士', phoneCode: '+41', countryCode: 'CH' },
  { countryName: '瑞典', phoneCode: '+46', countryCode: 'SE' },
  { countryName: '挪威', phoneCode: '+47', countryCode: 'NO' },
  { countryName: '丹麦', phoneCode: '+45', countryCode: 'DK' },
  { countryName: '芬兰', phoneCode: '+358', countryCode: 'FI' },
  { countryName: '比利时', phoneCode: '+32', countryCode: 'BE' },
  { countryName: '奥地利', phoneCode: '+43', countryCode: 'AT' },
  { countryName: '爱尔兰', phoneCode: '+353', countryCode: 'IE' },
  { countryName: '葡萄牙', phoneCode: '+351', countryCode: 'PT' },
  { countryName: '波兰', phoneCode: '+48', countryCode: 'PL' },
  { countryName: '希腊', phoneCode: '+30', countryCode: 'GR' },
  { countryName: '乌克兰', phoneCode: '+380', countryCode: 'UA' },
  { countryName: '土耳其', phoneCode: '+90', countryCode: 'TR' },
  { countryName: '匈牙利', phoneCode: '+36', countryCode: 'HU' },
  { countryName: '捷克', phoneCode: '+420', countryCode: 'CZ' },
  { countryName: '罗马尼亚', phoneCode: '+40', countryCode: 'RO' },

  // --- 大洋洲 Oceania ---
  { countryName: '澳大利亚', phoneCode: '+61', countryCode: 'AU' },
  { countryName: '新西兰', phoneCode: '+64', countryCode: 'NZ' },

  // --- 南美洲 South America ---
  { countryName: '巴西', phoneCode: '+55', countryCode: 'BR' },
  { countryName: '阿根廷', phoneCode: '+54', countryCode: 'AR' },
  { countryName: '智利', phoneCode: '+56', countryCode: 'CL' },
  { countryName: '哥伦比亚', phoneCode: '+57', countryCode: 'CO' },
  { countryName: '秘鲁', phoneCode: '+51', countryCode: 'PE' },

  // --- 中东与非洲 Middle East & Africa ---
  { countryName: '沙特阿拉伯', phoneCode: '+966', countryCode: 'SA' },
  { countryName: '阿联酋', phoneCode: '+971', countryCode: 'AE' },
  { countryName: '以色列', phoneCode: '+972', countryCode: 'IL' },
  { countryName: '埃及', phoneCode: '+20', countryCode: 'EG' },
  { countryName: '南非', phoneCode: '+27', countryCode: 'ZA' },
  { countryName: '尼日利亚', phoneCode: '+234', countryCode: 'NG' },
  { countryName: '肯尼亚', phoneCode: '+254', countryCode: 'KE' },
];
